function getRandomValue() {
    // Generer en tilfeldig verdi mellom 0 og 2 for svaralternativene
    return Math.floor(Math.random() * 10);
}

export const questions = [
    {
        question: "Høy skatt er bra for samfunnet",
        heltEnig: {
            Ap: getRandomValue(),
            Høyre: getRandomValue(),
            Frp: getRandomValue(),
            SV: getRandomValue(),
            Venstre: getRandomValue(),
            Sp: getRandomValue(),
            KrF: getRandomValue(),
            MDG: getRandomValue(),
            Rødt: getRandomValue(),
        },
        LittEnig: {
            Ap: getRandomValue(),
            Høyre: getRandomValue(),
            Frp: getRandomValue(),
            SV: getRandomValue(),
            Venstre: getRandomValue(),
            Sp: getRandomValue(),
            KrF: getRandomValue(),
            MDG: getRandomValue(),
            Rødt: getRandomValue(),
        },
        Littuenig: {
            Ap: getRandomValue(),
            Høyre: getRandomValue(),
            Frp: getRandomValue(),
            SV: getRandomValue(),
            Venstre: getRandomValue(),
            Sp: getRandomValue(),
            KrF: getRandomValue(),
            MDG: getRandomValue(),
            Rødt: getRandomValue(),
        },
        heltUenig: {
            Ap: getRandomValue(),
            Høyre: getRandomValue(),
            Frp: getRandomValue(),
            SV: getRandomValue(),
            Venstre: getRandomValue(),
            Sp: getRandomValue(),
            KrF: getRandomValue(),
            MDG: getRandomValue(),
            Rødt: getRandomValue(),
        }
    },
    {
        question: "Ost er godt!",
        heltEnig: {
            Ap: getRandomValue(),
            Høyre: getRandomValue(),
            Frp: getRandomValue(),
            SV: getRandomValue(),
            Venstre: getRandomValue(),
            Sp: getRandomValue(),
            KrF: getRandomValue(),
            MDG: getRandomValue(),
            Rødt: getRandomValue(),
        },
        LittEnig: {
            Ap: getRandomValue(),
            Høyre: getRandomValue(),
            Frp: getRandomValue(),
            SV: getRandomValue(),
            Venstre: getRandomValue(),
            Sp: getRandomValue(),
            KrF: getRandomValue(),
            MDG: getRandomValue(),
            Rødt: getRandomValue(),
        },
        Littuenig: {
            Ap: getRandomValue(),
            Høyre: getRandomValue(),
            Frp: getRandomValue(),
            SV: getRandomValue(),
            Venstre: getRandomValue(),
            Sp: getRandomValue(),
            KrF: getRandomValue(),
            MDG: getRandomValue(),
            Rødt: getRandomValue(),
        },
        heltUenig: {
            Ap: getRandomValue(),
            Høyre: getRandomValue(),
            Frp: getRandomValue(),
            SV: getRandomValue(),
            Venstre: getRandomValue(),
            Sp: getRandomValue(),
            KrF: getRandomValue(),
            MDG: getRandomValue(),
            Rødt: getRandomValue(),
        }
    },
    {
        question: "Bør Norge øke sin innsats for å bekjempe klimaendringer?",
        heltEnig: {
            Ap: getRandomValue(),
            Høyre: getRandomValue(),
            Frp: getRandomValue(),
            SV: getRandomValue(),
            Venstre: getRandomValue(),
            Sp: getRandomValue(),
            KrF: getRandomValue(),
            MDG: getRandomValue(),
            Rødt: getRandomValue(),
        },
        LittEnig: {
            Ap: getRandomValue(),
            Høyre: getRandomValue(),
            Frp: getRandomValue(),
            SV: getRandomValue(),
            Venstre: getRandomValue(),
            Sp: getRandomValue(),
            KrF: getRandomValue(),
            MDG: getRandomValue(),
            Rødt: getRandomValue(),
        },
        Littuenig: {
            Ap: getRandomValue(),
            Høyre: getRandomValue(),
            Frp: getRandomValue(),
            SV: getRandomValue(),
            Venstre: getRandomValue(),
            Sp: getRandomValue(),
            KrF: getRandomValue(),
            MDG: getRandomValue(),
            Rødt: getRandomValue(),
        },
        heltUenig: {
            Ap: getRandomValue(),
            Høyre: getRandomValue(),
            Frp: getRandomValue(),
            SV: getRandomValue(),
            Venstre: getRandomValue(),
            Sp: getRandomValue(),
            KrF: getRandomValue(),
            MDG: getRandomValue(),
            Rødt: getRandomValue(),
        }
    },
    {
        question: "Skal det være flere offentlige helsetjenester?",
        heltEnig: {
            Ap: getRandomValue(),
            Høyre: getRandomValue(),
            Frp: getRandomValue(),
            SV: getRandomValue(),
            Venstre: getRandomValue(),
            Sp: getRandomValue(),
            KrF: getRandomValue(),
            MDG: getRandomValue(),
            Rødt: getRandomValue(),
        },
        LittEnig: {
            Ap: getRandomValue(),
            Høyre: getRandomValue(),
            Frp: getRandomValue(),
            SV: getRandomValue(),
            Venstre: getRandomValue(),
            Sp: getRandomValue(),
            KrF: getRandomValue(),
            MDG: getRandomValue(),
            Rødt: getRandomValue(),
        },
        Littuenig: {
            Ap: getRandomValue(),
            Høyre: getRandomValue(),
            Frp: getRandomValue(),
            SV: getRandomValue(),
            Venstre: getRandomValue(),
            Sp: getRandomValue(),
            KrF: getRandomValue(),
            MDG: getRandomValue(),
            Rødt: getRandomValue(),
        },
        heltUenig: {
            Ap: getRandomValue(),
            Høyre: getRandomValue(),
            Frp: getRandomValue(),
            SV: getRandomValue(),
            Venstre: getRandomValue(),
            Sp: getRandomValue(),
            KrF: getRandomValue(),
            MDG: getRandomValue(),
            Rødt: getRandomValue(),
        }
    }
];



// Du har nå totalt ti spørsmål i ditt spørsmålssett. Du kan legge til flere spørsmål på samme måte som de over.
